// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopData;

namespace ShopData.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20191104224847_SetColWidths")]
    partial class SetColWidths
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopDomain.Entities.Product", b =>
                {
                    b.Property<int>("_productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProductId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("_description")
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(512)")
                        .HasMaxLength(512);

                    b.Property<string>("_name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<decimal>("_price")
                        .HasColumnName("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("_productId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ShopDomain.Entities.Review", b =>
                {
                    b.Property<int>("_reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ReviewId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Product_productId")
                        .HasColumnType("int");

                    b.Property<int?>("Product_productId1")
                        .HasColumnType("int");

                    b.Property<int>("_rating")
                        .HasColumnName("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("_reviewDate")
                        .HasColumnName("ReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("_reviewText")
                        .HasColumnName("ReviewText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_reviewer")
                        .HasColumnName("Reviewer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_reviewId");

                    b.HasIndex("Product_productId");

                    b.HasIndex("Product_productId1");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ShopDomain.Entities.Review", b =>
                {
                    b.HasOne("ShopDomain.Entities.Product", null)
                        .WithMany("Reviews")
                        .HasForeignKey("Product_productId");

                    b.HasOne("ShopDomain.Entities.Product", null)
                        .WithMany("_reviews")
                        .HasForeignKey("Product_productId1");
                });
#pragma warning restore 612, 618
        }
    }
}
