// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopData;

namespace ShopData.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20191104223905_InitialProduct")]
    partial class InitialProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopDomain.Entities.Product", b =>
                {
                    b.Property<int>("_productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("_productId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ShopDomain.Entities.Review", b =>
                {
                    b.Property<int>("_reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Product_productId")
                        .HasColumnType("int");

                    b.Property<int?>("Product_productId1")
                        .HasColumnType("int");

                    b.HasKey("_reviewId");

                    b.HasIndex("Product_productId");

                    b.HasIndex("Product_productId1");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ShopDomain.Entities.Review", b =>
                {
                    b.HasOne("ShopDomain.Entities.Product", null)
                        .WithMany("Reviews")
                        .HasForeignKey("Product_productId");

                    b.HasOne("ShopDomain.Entities.Product", null)
                        .WithMany("_reviews")
                        .HasForeignKey("Product_productId1");
                });
#pragma warning restore 612, 618
        }
    }
}
